<a href="https://colab.research.google.com/github/augustolnb/Minicursos/blob/main/minicurso_python_para_engenharia.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Conteúdo programático**

- Comandos básicos - if/else, for, while, print, input
- O básico sobre formatação - int, float, string, array
- Operadores algébricos e lógicos
- Matrizes e gráficos
- Bibliotecas úteis [numpy, scipy, math]
- Biblioteca symbolic (derivada e integral)



*Links úteis*

- *https://www.facom.ufu.br/~william/Disciplinas%202019-1/BIOTCH-GBT017-IntoducaoInformatica/285173966-aprendendo-python-pdf.pdf*


- *https://acristoffers.me/Python3.pdf*

#### Comandos básicos de entrada e saída de dados


In [ ]:
nome = input("Digite seu nome: ")

print("Hello World, {} !".format(nome))


Digite seu nome: megatron
Hello World, megatron !


#### Operadores lógicos e matemáticos

In [ ]:
print("\tCalculadora que faz soma de dois valores\n")

n1 = input("Entre com o primeiro número: ")
n2 = input("Entre com o segundo número: ")

print("O resultado da soma {} + {} = {}".format(n1, n2, n1+n2))

	Calculadora que faz soma de dois valores

Entre com o primeiro número: 5
Entre com o segundo número: 3
O resultado da soma 5 + 3 = 53


In [ ]:
print("\tImprime apenas os números maiores que 10\n")

numero = input("Digite um número: ")

if(numero >= 10):
    print("O número é : {}".format(numero))

else:
    print("O número é menor que 10")

	Imprime apenas os números maiores que 10

Digite um número: 12
O número é : 12


In [ ]:
print("\tExemplo de contador com o laço while\n")

iteracoes = input("Digite a quatidade de iterações que deseja fazer: ")

i = 0
while i <= iteracoes:
    print("{}ª Iteração".format(iteracoes))
    i += 1

Exemplo de contador com o laço while
Digite a quatidade de iterações que deseja fazer: 6
1ª Iteração
2ª Iteração
3ª Iteração
4ª Iteração
5ª Iteração
6ª Iteração


In [ ]:
print("\tCriando o primeiro laço for\n")

iteracoes = input("Quantas iteracoes o laço deve realizar?")

for i in range(iteracoes):
    print("Funcionou {}x".format(i))

	Criando o primeiro laço for

Quantas iteracoes o laço deve realizar?10
Funcionou 1x
Funcionou 2x
Funcionou 3x
Funcionou 4x
Funcionou 5x
Funcionou 6x
Funcionou 7x
Funcionou 8x
Funcionou 9x
Funcionou 10x


#### Matemática computacional com Numpy

In [1]:
# importa a biblioteca numpy e "apelida" essa biblioteca de np
import numpy as np 

In [ ]:
# O método `np.array` cria um array numpy com seus próprios valores.
one_dimensional_array = np.array([1.2, 2.4, 3.5, 4.7, 6.1, 7.2, 8.3, 9.5])
print(one_dimensional_array)
print("\n\n")
two_dimensional_array = np.array([[6, 5], [11, 7], [4, 8]])
print(two_dimensional_array)

[1.2 2.4 3.5 4.7 6.1 7.2 8.3 9.5]



[[ 6  5]
 [11  7]
 [ 4  8]]


In [ ]:
# Também é possível preencher um array com um sequência de números utilizando o método arange()
sequence_of_integers = np.arange(5, 12)
print(sequence_of_integers)

print("\n\n\n")

# Preenchendo arrays com valores aleátorios

random_integers_between_50_and_100 = np.random.randint(low=50, high=101, size=(6))
print("Números aleatórios entre 50 e 100: ")
print(random_integers_between_50_and_100)
print("\n")
print("Números aleatórios entre 0 e 1: ")
random_floats_between_0_and_1 = np.random.random([6])
print(random_floats_between_0_and_1) 

[ 5  6  7  8  9 10 11]




Números aleatórios entre 50 e 100: 
[84 59 91 98 92 79]


Números aleatórios entre 0 e 1: 
[0.39324895 0.26207961 0.67601699 0.26928658 0.60992404 0.54384921]


Se você quiser adicionar ou subtrair dois arrays, a álgebra linear requer que os dois operandos tenham as mesmas dimensões. Além disso, se você quiser multiplicar dois arrays, a álgebra linear impõe regras estritas sobre a compatibilidade dimensional dos operandos. Felizmente, a NumPy usa um truque chamado *broadcast* para virtualmente expandir o operando menor para dimensões compatíveis para a álgebra linear.

In [ ]:
random_floats_between_2_and_3 = random_floats_between_0_and_1 + 2.0
print(random_floats_between_2_and_3)

[2.39324895 2.26207961 2.67601699 2.26928658 2.60992404 2.54384921]


In [ ]:
random_integers_between_150_and_300 = random_integers_between_50_and_100 * 3
print(random_integers_between_150_and_300)

[252 177 273 294 276 237]


#### Desafio 1:

- Montar uma calculadora para converter valores de cartesiano para polar

In [2]:
# Implementar calculadora polar <-> cartesiano

def pol2rec(amp, fase):
    amp = float(amp)
    fase = float(fase)
    real = amp*np.cos(fase/180*np.pi)
    imag = amp*np.sin(fase/180*np.pi)
    return complex(round(real,2),round(imag,2))

def rec2pol(real, imag):
    real = float(real)
    imag = float(imag)
    amp = np.sqrt(real**2 + imag**2)
    fase = np.arctan(imag/real)*180/np.pi
    # consertar retorno duplo e indexar os valores no mesmo formato
    return float(round(amp,2)), float(round(fase,2))


In [11]:
import os
from google.colab import output

while True:
    print("\tConversão entre as coordenadas polar e cartesiana.\n")
    op = int(input("Escolha a conversão:\n1: Polar -> Cartesiano\n2: Cartesiano -> Polar\n3: Sair\n\n"))

    if(op == 1):
        print("Entre com os valores de amplitude e fase: ")
        amplitude = float(input("Amplitude: "))
        fase = float(input("Fase: "))
        coord_cart = pol2rec(amplitude, fase)
        print("{}".format(coord_cart))
        input("\nPressione para continuar\n")

    elif(op == 2):
        print("Entre com as partes do número complexo: ")
        real = float(input("Parte real: "))
        imaginaria = float(input("Parte imaginária: "))
        amp, fase = rec2pol(real, imaginaria)
        print("\nAmplitude: {}\nFase: {}º".format(amp, fase))
        input("\n   Pressione para continuar\n")

    elif(op == 3):
        break

    else: 
        print("Entre com uma opção válida")
    
    output.clear()


	Conversão entre as coordenadas polar e cartesiana.

Escolha a conversão:
1: Polar -> Cartesiano
2: Cartesiano -> Polar
3: Sair

1
Entre com os valores de amplitude e fase: 
Amplitude: 1
Fase: 25
(0.91+0.42j)


TypeError: ignored

#### Biblioteca Sympy

In [10]:
!pip install sympy

import sympy as sp

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
